### ISSUE TITLE
GraphQL result doesn't preserve fields query order

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphql-core-legacy#18]
When querying a GraphQL schema, the GraphQL result doesn't preserve fields query order.

Based on this Gist:
https://gist.github.com/syrusakbary/d116212d3a1f688519c2

**Comment by syrusakbary** [comment]
It seems to be fixed in latest version by the following PR https://github.com/graphql-python/graphql-core/pull/15
Closing issue.

**Comment by jhgg** [comment]
@syrusakbary, I wouldn't be too sure about that! The effects you are seeing/testing for https://github.com/graphql-python/graphql-relay-py/commit/aafe5c34319102a26ae08b394d22777fce1d880f is purely coincidential. I have not implemented any ordering guarantees for the fields in the results. 

The only ordering guarantee I have made is that:
a) When fields are defined in an `GraphQLObjectType`, `GraphQLInputObjectType` and `GraphQLEnumType`, if they are passed in as an `OrderedDict`, we will keep their ordering, so that the results of any Introspection query remains stable.
b) When issuing a mutation, or setting `execute_serially` to True in the `Executor`, the ordering of which resolve functions to execute will match the order they are defined in the Query's Definitions.

**Comment by jhgg** [comment]
As far as the specification goes, the responses should have no order:

https://facebook.github.io/graphql/#sec-Objects

> A query of an object value must select at least one field. This selection of fields will yield an **unordered map** containing exactly the subset of the object queried. Only fields that are declared on the object type may validly be queried on that object.

This would mean that the tests in https://github.com/graphql-python/graphql-relay-py/commit/aafe5c34319102a26ae08b394d22777fce1d880f are wrong. 

I'm going to go ahead and close this issue again @syrusakbary. I would recommend reverting that commit. As it's testing for behavior that only coincidentally exists.

**Comment by syrusakbary** [comment]
I check both orders ({name, id} and {id, name}) and seems to work well.
