### ISSUE TITLE
mypy reports invalid syntax with validators/rules/overlapping_fields_can_be_merged.py:344

### ISSUE THREAD

**Issue by achimnol** [graphql-python/graphql-core-legacy#263]
The line 344 and 345 in `overlapping_fields_can_be_merged.py` causes mypy 0.761 to report invalid syntax error during type checks.

My program with graphql-core runs just fine at runtime and in fact those lines are in a valid Python syntax though look strange (orphaned expressions).

But I think if they aren't intended codes, then I'd like to suggest to fix them.

Here is [the CI report link.](https://github.com/lablup/backend.ai-manager/runs/406488966)

**Comment by achimnol** [comment]
This might be related to python/mypy#8218.

**Comment by Cito** [comment]
Thank you for reporting this @achimnol. I believe these two lines have been accidentally copied into the code when Syrus added the type hints, since these serve no purpose as you already noticed.

I have removed the lines now completely. Interestingly, they were not detected by our CI. I found the difference was that your CI is using Python 3.8 and ours Python 3.7. It seems mypy behaves differently depending on the Python version.

**Comment by benhowes** [comment]
Would it be possible to get a release of this please :pray:

And thanks so much for resolving so quickly!

**Comment by Cito** [comment]
New release 2.3.1 with this and a few other minor fixes is out now. 😄

**Comment by achimnol** [comment]
Thanks!
